doctrine_mongodb:
  auto_generate_proxy_classes: true
  auto_generate_hydrator_classes: true
  connections:
    default:
      server: 'mongodb://localhost:27017'
  default_database: 'garage_db'
  document_managers:
    default:
      auto_mapping: true
      mappings:
        App:
          dir: "%kernel.project_dir%/src/Document"
          mapping: true
          type: attribute
          prefix: 'App\Document'
          is_bundle: false
          alias: App
