controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
app_voitures_occasion:
    path: /voitures-occasion
    controller: App\Controller\VoitureController::index
